name = "grassrootsmvt"

# Pages configuration (Pages-only file)
pages_build_output_dir = "ui"
project_name = "grassrootsmvt"
functions = "ui/functions"

[vars]
ENVIRONMENT = "local"
ALLOW_ORIGIN = "http://localhost:8788"
