name = "grassrootsmvt"
compatibility_date = "2024-01-01"

# Optional: Environment vars for local dev
[vars]
ENVIRONMENT = "local"
ALLOW_ORIGIN = "http://localhost:8788"

# ✅ This tells Wrangler (and Pages) where to find your functions.
functions = "ui/functions"

# ✅ Cloudflare Pages build output (UI directory)
pages_build_output_dir = "ui"
