name = "grassrootsmvt"
compatibility_date = "2024-01-01"

# Optional: Environment vars for local dev
[vars]
ENVIRONMENT = "local"
ALLOW_ORIGIN = "http://localhost:8788"

[pages]
project_name = "grassrootsmvt"
pages_build_output_dir = "ui"
functions = "ui/functions"
