name = "grassrootsmvt"

# Top-level Pages build output dir (some Wrangler versions expect this)
pages_build_output_dir = "ui"

[vars]
ENVIRONMENT = "local"
ALLOW_ORIGIN = "http://localhost:8788"

[pages]
project_name = "grassrootsmvt"
pages_build_output_dir = "ui"
functions = "ui/functions"
