name = "grassroots-api"
main = "src/index.ts"
compatibility_date = "2025-09-30"

# D1 (prod)
[[d1_databases]]
binding = "wy"
database_name = "wy"
database_id = "4b4227f1-bf30-4fcf-8a08-6967b536a5ab"
migrations_dir = "../db/migrations"   # <- fixed

[vars]
ACCESS_HEADER = "Cf-Access-Authenticated-User-Email"
DATA_BACKEND = "d1"
DEV_EMAIL = "dev@local"

# Public API route (prod)
[[routes]]
pattern = "api.grassrootsmvt.org/*"
zone_name = "grassrootsmvt.org"

[[routes]]
pattern = "volunteers.grassrootsmvt.org/api/*"
zone_name = "grassrootsmvt.org"
