# .github/workflows/deploy-ui.yml
name: Deploy UI (Pages)

on:
  push:
    branches: [ main ]
    paths: [ 'ui/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Wrangler
        run: npm i -g wrangler@latest
      - name: Deploy to Pages
        run: wrangler pages deploy ./ui --project-name grassrootsmvt
