---
name: "🧪 Validate Workflow YAML + CI consistency"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: "🧩 Validate Workflows"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "🧰 Install YAML and JSON tools"
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y python3-pip jq
          pip install yamllint
          npm install -g js-yaml

      - name: "🔍 Lint all YAML workflows"
        run: |
          echo "🧪 Running yamllint..."
          yamllint .github/workflows
          echo "🧩 Validating YAML syntax with js-yaml..."
          for f in .github/workflows/*.yml; do
            echo "Checking $f..."
            npx js-yaml "$f" >/dev/null || { echo "❌ Invalid YAML in $f"; exit 1; }
          done
          echo "✅ YAML syntax validated successfully."

      - name: "📂 Check working-directory consistency"
        if: false
        run: |
          echo "🔍 Ensuring all wrangler deploy commands run from ui/..."
          BAD_PATHS=$(grep -r "npx wrangler" .github/workflows | grep -v "working-directory: ui" || true)
          if [[ -n "$BAD_PATHS" ]]; then
            echo "❌ Found wrangler commands not using working-directory: ui/"
            echo "$BAD_PATHS"
            exit 1
          fi
          echo "✅ All wrangler commands are correctly scoped to ui/."

      - name: "🔐 Verify required environment secrets"
        run: |
          echo "🔍 Verifying that required secrets are configured..."
          REQUIRED=("CLOUDFLARE_API_TOKEN" "CLOUDFLARE_ACCOUNT_ID" "PROJECT")
          MISSING=()
          for VAR in "${REQUIRED[@]}"; do
            if ! echo "${{ toJson(secrets) }}" | jq -e ".${VAR}" >/dev/null; then
              MISSING+=("$VAR")
            fi
          done
          if [ "${#MISSING[@]}" -gt 0 ]; then
            echo "❌ Missing required secrets: ${MISSING[*]}"
            exit 1
          fi
          echo "✅ All required secrets are present."

      - name: "🧠 Confirm file structure"
        run: |
          echo "🔍 Verifying required files exist..."
          REQUIRED_FILES=("ui/wrangler.toml" "ui/functions" "scripts/verify_deploy.mjs" ".github/workflows/deploy.yml")
          for FILE in "${REQUIRED_FILES[@]}"; do
            if [ ! -e "$FILE" ]; then
              echo "❌ Missing required file or directory: $FILE"
              exit 1
            fi
          done
          echo "✅ File structure OK."

      - name: "✨ Validation Summary"
        run: |
          echo ""
          echo "✅ All validation checks passed — workflows are safe to deploy."
